// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// EndemicTable
NumericVector EndemicTable(NumericVector tax, NumericVector loc, int proportion);
RcppExport SEXP _obigeo_EndemicTable(SEXP taxSEXP, SEXP locSEXP, SEXP proportionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tax(taxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type loc(locSEXP);
    Rcpp::traits::input_parameter< int >::type proportion(proportionSEXP);
    rcpp_result_gen = Rcpp::wrap(EndemicTable(tax, loc, proportion));
    return rcpp_result_gen;
END_RCPP
}
// ChangeIndexTwo
NumericVector ChangeIndexTwo(NumericVector one, NumericVector two);
RcppExport SEXP _obigeo_ChangeIndexTwo(SEXP oneSEXP, SEXP twoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type one(oneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type two(twoSEXP);
    rcpp_result_gen = Rcpp::wrap(ChangeIndexTwo(one, two));
    return rcpp_result_gen;
END_RCPP
}
// ChangeIndexThree
NumericVector ChangeIndexThree(NumericVector one, NumericVector two, NumericVector three);
RcppExport SEXP _obigeo_ChangeIndexThree(SEXP oneSEXP, SEXP twoSEXP, SEXP threeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type one(oneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type two(twoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type three(threeSEXP);
    rcpp_result_gen = Rcpp::wrap(ChangeIndexThree(one, two, three));
    return rcpp_result_gen;
END_RCPP
}
// RangeRarity
NumericVector RangeRarity(NumericVector locVec, NumericVector taxVec, NumericVector propVec, NumericVector occup);
RcppExport SEXP _obigeo_RangeRarity(SEXP locVecSEXP, SEXP taxVecSEXP, SEXP propVecSEXP, SEXP occupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type locVec(locVecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taxVec(taxVecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type propVec(propVecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type occup(occupSEXP);
    rcpp_result_gen = Rcpp::wrap(RangeRarity(locVec, taxVec, propVec, occup));
    return rcpp_result_gen;
END_RCPP
}
