# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EndemicTable <- function(tax, loc, proportion) {
    .Call(`_obigeo_EndemicTable`, tax, loc, proportion)
}

ChangeIndexTwo <- function(one, two) {
    .Call(`_obigeo_ChangeIndexTwo`, one, two)
}

ChangeIndexThree <- function(one, two, three) {
    .Call(`_obigeo_ChangeIndexThree`, one, two, three)
}

RangeRarity <- function(locVec, taxVec, propVec, occup) {
    .Call(`_obigeo_RangeRarity`, locVec, taxVec, propVec, occup)
}

